// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXl2UbVp4DuFjl7WWL_NRz9fotpteTbAs',
    appId: '1:929049411073:web:5140d127ec96a5ca04ca00',
    messagingSenderId: '929049411073',
    projectId: 'login-ec993',
    authDomain: 'login-ec993.firebaseapp.com',
    storageBucket: 'login-ec993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI1HWjZsHXYD7nho4yaayDTfs1SH1dfJg',
    appId: '1:929049411073:android:979e4e960a9e3afa04ca00',
    messagingSenderId: '929049411073',
    projectId: 'login-ec993',
    storageBucket: 'login-ec993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmL_9QPiCeTpVG71aQUQLg32EVKrgugNc',
    appId: '1:929049411073:ios:d8f4205cba0ac47604ca00',
    messagingSenderId: '929049411073',
    projectId: 'login-ec993',
    storageBucket: 'login-ec993.appspot.com',
    iosClientId: '929049411073-u5vudfnqsm29r8i5toibucj33bmbi5f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmL_9QPiCeTpVG71aQUQLg32EVKrgugNc',
    appId: '1:929049411073:ios:0f1ff36ad5b7e3ed04ca00',
    messagingSenderId: '929049411073',
    projectId: 'login-ec993',
    storageBucket: 'login-ec993.appspot.com',
    iosClientId: '929049411073-7h6u7ktr6s5foq3eiqe4jn236f6acn16.apps.googleusercontent.com',
    iosBundleId: 'com.example.tes.RunnerTests',
  );
}
